language: android
install:
  - ./gradlew assembleDebug
script:
  - ./gradlew test
addons:
  browserstack:
    username: pankajahuja
    access_key: aCxhDStUopf8tsyz4d55
    app_path: "browserstack_android_sample/build/outputs/apk/debug/browserstack_android_sample-debug.apk"
