language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools
before_install:
  - yes | sdkmanager "platforms;android-27"
install:
  - ./gradlew assembleDebug
script:
  - echo $BROWSERSTACK_APP_ID
  - ./gradlew test
addons:
  browserstack:
    username: "pankajahuja"
    access_key: "aCxhDStUopf8tsyz4d55"
app_path: "browserstack_android_sample/build/outputs/apk/debug/browserstack_android_sample-debug.apk"
